FROM nginx:alpine
COPY static /usr/share/nginx/html/static
COPY index.html /usr/share/nginx/html/index.html
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY static/logo_small.png /usr/share/nginx/html/favicon.png