events {}
http {
    client_max_body_size 100M;
    server {
        listen 80;
        server_name cfdnsmanager.geri.app;

        location /app/osx/update.json {
            proxy_pass http://app:5000/update.json;
            proxy_set_header Host $host;
        }

        location /upload {
            proxy_pass http://app:5000/upload;
            proxy_set_header Host $host;
        }

        location /app/osx/ {
            alias /usr/share/nginx/html/app/osx/;
            autoindex on;
        }

        location / {
            proxy_pass http://website:4445/;
            proxy_set_header Host $host;
        }
    }
} 