name: Build and Upload macOS DMG

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'build/*'

jobs:
  build-macos-dmg:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          brew install create-dmg

      - name: Set version in kivyapp.py
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          VERSION=${GITHUB_REF#refs/tags/}
          echo "$VERSION" > version.txt
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sed -i '' "s/^APP_VERSION = .*/APP_VERSION = \"$VERSION\"/" kivyapp.py
          cat kivyapp.py | grep APP_VERSION

      - name: Build app
        run: |
          pyinstaller --windowed --noconfirm --clean \
            --name "Cloudflare DNS Manager" \
            --icon cfguiosx512.icns \
            --add-data "cfguiosx512.icns:." \
            --add-data "cfguiosx512.png:." \
            --add-data "Cloudflare32px.png:." \
            --add-data "Cloudflare32px_gray.png:." \
            --add-data "Cloudflare32px.icns:." \
            --add-data "Cloudflare32px.ico:." \
            kivyapp.py

      - name: Prepare DMG folder
        run: |
          rm -rf installer_dmg
          mkdir -p installer_dmg
          cp -R "dist/Cloudflare DNS Manager.app" installer_dmg/
          ln -s /Applications installer_dmg/Applications

      - name: Create DMG
        run: |
          create-dmg \
            --volname "Cloudflare DNS Manager" \
            --window-size 500 300 \
            --icon-size 120 \
            --icon "Cloudflare DNS Manager.app" 100 120 \
            --icon "Applications" 380 120 \
            --app-drop-link 380 120 \
            CloudflareDNSManager.dmg \
            installer_dmg/
          echo "DMG_PATH=CloudflareDNSManager.dmg" >> $GITHUB_ENV

      - name: Upload DMG to update server
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          DMG_PATH: ${{ env.DMG_PATH }}
        run: |
          VERSION=$(cat version.txt)
          echo "Uploading version: $VERSION, DMG: $DMG_PATH"
          if [ -z "$DMG_PATH" ]; then
            echo "No .dmg file found!"
            exit 1
          fi
          if [ -z "$VERSION" ]; then
            echo "No version found!"
            exit 1
          fi
          curl -X POST https://cfdnsmanager.geri.app/upload \
            -F "key=$UPLOAD_KEY" \
            -F "version=$VERSION" \
            -F "dmg=@$DMG_PATH" 